name: MapReflectionAPI
version: '${project.version}'
main: tech.sbdevelopment.mapreflectionapi.MapReflectionAPI
api-version: 1.13
authors: [ inventivetalent, SBDeveloper ]
description: This API helps developer with viewing images on maps.
website: https://sbdevelopment.tech
softdepend: [ BKCommonLib, ProtocolLib ]